### ISSUE TITLE
Sometimes Activity crashing when get String Resources Resources$NotFoundException

### ISSUE THREAD

**Issue by JosephSanjaya** [B3nedikt/restring#110]
## Context (Environment)
Restring version: `5.2.1`
Android version: `occured randomly on all devices`

## Summary
Activity crashing without reason that happen sporadically, when we check our resources its there, but sometimes it still crash `Resources$NotFoundException`. 
```
RestringResources.kt line 182
dev.b3nedikt.restring.internal.RestringResources.openRawResourceFd 
```

## Expected Behavior
Activity not crashing at all

## Current Behavior
Activity crash randomly with Resources$NotFoundException

## Stack trace
```
Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7b090013
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:259)
       at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:368)
       at android.content.res.Resources.openRawResourceFd(Resources.java:1336)
       at dev.b3nedikt.restring.internal.RestringResources.openRawResourceFd(RestringResources.kt:182)
       at android.media.MediaPlayer.create(MediaPlayer.java:1029)
       at android.media.MediaPlayer.create(MediaPlayer.java:1012)
       at androidx.fragment.app.Fragment.performStop(Fragment.java:3184)
       at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:640)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:3096)
       at androidx.fragment.app.Fragment.performStop(Fragment.java:3177)
       at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:640)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:3096)
       at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:295)
       at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:525)
       at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:252)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1473)
       at android.app.Activity.performStop(Activity.java:8217)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4958)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5609)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5544)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:227)
       at android.app.ActivityThread.main(ActivityThread.java:7822)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

**Comment by B3nedikt** [comment]
At first glance this does not look to be related to restring, the crash occurs after opening a raw resource with the `MediaPlayer` API. Restring does only delegate the `openRawResourceFd` call to the framework API, as you can also see in the stack trace you posted. I cannot exclude it though ;) Could you fork this repository, and change the example code, so that it is as close to your production code with the `MediaPlayer` API as possible? Maybe the crash can be reproduced this way.

**Comment by JosephSanjaya** [comment]
actually it occured not only in `MediaPlayer` api sir. Here ini another crash stack strace. sometimes it occured also when application in resume state. any idea how it can happen?

```
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x7e08001e
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:264)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2415)
       at android.content.res.Resources.getLayout(Resources.java:1261)
       at dev.b3nedikt.restring.internal.RestringResources.getLayout(RestringResources.kt:162)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:530)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
       at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at android.app.Activity.performStart(Activity.java:8175)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3774)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2341)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8258)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by B3nedikt** [comment]
Similar situation as with the `MediaPlayer`, restring only forwards the call here, the crash happens in the framework. Are you sure this crash does also occur without restring? No specific idea, common reasons for this kind of issues are bugs of the AppCompat library or wrong integration of libraries which manipulate resources like restring. So maybe I can find a issue if you post the libraries and versions you use.

**Comment by B3nedikt** [comment]
Solved I guess?

**Comment by liandara** [comment]
Hi @B3nedikt i'am from the same company with Joseph, and we still got this issue always occurred and appear on our firebase crashlytic. Have you applied this libs in dynamic feature module? because the issue occur only on it. Might be you can share the implementations in dynamic feature module. Thank you 🙇‍♀️

**Comment by B3nedikt** [comment]
Hi @liandara :) I have never used it in a dynamic feature module myself, but others who use it seem to not have a problem. I don't think there is any specific configuration necessary. It is hard for me to help out here, as I lack information on how you use dynamic feature modules exactly, and when the crash occurs. So I assume from the ticket, that the crash is not reproduceable for you, meaning you can only see it for some users in crashlytics? Does is maybe only occur on specific device types?
