### ISSUE TITLE
Viewpump inflater resource not found on P

### ISSUE THREAD

**Issue by ngpambudi** [B3nedikt/restring#36]
`Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x0
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2167)
       at android.content.res.Resources.getLayout(Resources.java:1167)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:695)
       at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
       at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
       at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
       at android.app.Dialog.show(Dialog.java:302)`

This error appear in some device and works on another device, and also appeat in random popup/custom view

**Comment by ngpambudi** [comment]
I found the solution refer to issue #34 

Thanks
