### ISSUE TITLE
Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}

### ISSUE THREAD

**Issue by Guy1982** [B3nedikt/restring#37]
Hi,
I'm getting an exception when trying to create a new instance of TextView with a context that was wrapped with Restring wrapper.

2020-08-23 16:13:31.542 11229-11229/com.tytocare W/System.err: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
2020-08-23 16:13:31.542 11229-11229/com.tytocare W/System.err:     at android.content.res.TypedArray.getColorStateList(TypedArray.java:538)
2020-08-23 16:13:31.543 11229-11229/com.tytocare W/System.err:     at android.widget.TextView.<init>(TextView.java:1239)
2020-08-23 16:13:31.543 11229-11229/com.tytocare W/System.err:     at android.widget.TextView.<init>(TextView.java:1129)
2020-08-23 16:13:31.543 11229-11229/com.tytocare W/System.err:     at android.widget.TextView.<init>(TextView.java:1125)
2020-08-23 16:13:31.543 11229-11229/com.tytocare W/System.err:     at android.widget.TextView.<init>(TextView.java:1121)

**Comment by Guy1982** [comment]
So I found the fix here:
https://stackoverflow.com/questions/19186235/how-to-change-app-default-theme-to-a-different-app-theme

Added:
<item name="colorAccent">@color/colorAccent</item>
 <item name="android:colorAccent">@color/colorAccent</item>

To my application theme and the crash stopped.

**Comment by Guy1982** [comment]
In the end, I made RestringContextWrapper inherit from ContextWrapper and not ContextThemeWrapper.
Was there a special reason to use ContextThemeWrapper and not ContextWrapper?

**Comment by B3nedikt** [comment]
Thanks for the report, no there was no special reason. I will fix it and release a new version.

**Comment by B3nedikt** [comment]
Fixed in version 4.0.6!

**Comment by Guy1982** [comment]
Thanks!
