### ISSUE TITLE
Lateinit stringRepository crashes on latest version

### ISSUE THREAD

**Issue by edgar-zigis** [B3nedikt/restring#52]
Hey @B3nedikt , apparently the issues with stringRepository are still present in Restring 5.x versions:

```
Caused by kotlin.UninitializedPropertyAccessException: lateinit property stringRepository has not been initialized
       at dev.b3nedikt.restring.Restring.wrapContext(Restring.java:110)
       at com.paysera.core.architecture.BaseActivity.attachBaseContext(BaseActivity.java:104)
       at android.app.Activity.attach(Activity.java:7982)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
```

But only few devices are crashing: Huawei Honor 8X and Samsung S8

**Comment by B3nedikt** [comment]
@edgar-zigis Now in Restring 5.1.0 the crash is fixed at least. However I am unsure how you got in this state, you do call Restring.init() in your application class?

**Comment by edgar-zigis** [comment]
Yeah, we call it in application class onCreate before any activity is laid out.

**Comment by B3nedikt** [comment]
@edgar-zigis Interesting, this suggests it is somehow cleaned up. I think the best solution to the problem, would be to delay creation of the repository to Restring.wrapContext(), by making Restring.stringRepository take a factory that creates a StringRepository. I am looking into this...

**Comment by edgar-zigis** [comment]
This issue occurs only with a few OEM's (Huawei always brings issues everywhere). I think that OS somehow might dispose some stuff during runtime. Unfortunately till Android has no universal standards, such things will occur :/ 
Fortunately it is not a re-occurring thing as crashes are singular and users can still use the app.
I will update to 5.1.0 on Wednesday (needed to revert Restring last time as crash with TextView was persistent and massive).
