### ISSUE TITLE
ViewPump issues

### ISSUE THREAD

**Issue by edgar-zigis** [B3nedikt/restring#53]
Hey, because issues are not available on your viewPump fork, I am placing them here:

There is an occasional exception here:

**1.**
```
Caused by java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0403ae a=-1}
       at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:948)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:932)
       at android.view.View.<init>(View.java:5019)
       at android.view.ViewGroup.<init>(ViewGroup.java:659)
       at android.widget.RelativeLayout.<init>(RelativeLayout.java:248)
       at android.widget.RelativeLayout.<init>(RelativeLayout.java:244)
       at android.widget.RelativeLayout.<init>(RelativeLayout.java:240)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:651)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater$NameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.java:294)
       at dev.b3nedikt.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.java:14)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.reword.RewordInterceptor.intercept(RewordInterceptor.java:13)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.viewpump.ViewPump.inflate(ViewPump.java:38)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.java:172)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:724)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.superOnCreateView(-ViewPumpLayoutInflater.java:237)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.access$superOnCreateView(-ViewPumpLayoutInflater.java:18)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater$ParentAndNameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.java:275)
       at dev.b3nedikt.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.java:14)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.reword.RewordInterceptor.intercept(RewordInterceptor.java:13)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.viewpump.ViewPump.inflate(ViewPump.java:38)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.java:154)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:792)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:51)
       at com.paysera.paymentTemplates.fragments.TemplateNameFragment.onCreateView(TemplateNameFragment.java:25)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

it comes together with this:

```
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:651)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater$NameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.java:294)
       at dev.b3nedikt.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.java:14)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.reword.RewordInterceptor.intercept(RewordInterceptor.java:13)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.viewpump.ViewPump.inflate(ViewPump.java:38)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.java:172)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:724)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.superOnCreateView(-ViewPumpLayoutInflater.java:237)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.access$superOnCreateView(-ViewPumpLayoutInflater.java:18)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater$ParentAndNameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.java:275)
       at dev.b3nedikt.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.java:14)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.reword.RewordInterceptor.intercept(RewordInterceptor.java:13)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.viewpump.ViewPump.inflate(ViewPump.java:38)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.java:154)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:792)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:51)
       at com.paysera.paymentTemplates.fragments.TemplateNameFragment.onCreateView(TemplateNameFragment.java:25)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
And the most important trace which comes with it:
`Caused by android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>`
Crash occurs only in Android 7, 8 and 9. No idea why class is unknown.

**2.**
Another occasional exception:

```
Caused by java.lang.UnsupportedOperationException: Failed to resolve attribute at index 37: TypedValue{t=0x2/d=0x7f0402c4 a=-1}
       at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:781)
       at android.view.View.<init>(View.java:5620)
       at android.widget.TextView.<init>(TextView.java:984)
       at android.widget.TextView.<init>(TextView.java:978)
       at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:100)
       at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:93)
       at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:88)
       at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:83)
       at com.google.android.material.theme.MaterialComponentsViewInflater.createTextView(MaterialComponentsViewInflater.java:61)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:115)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1551)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1602)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2ViewCreator.onCreateView(-ViewPumpLayoutInflater.java:390)
       at dev.b3nedikt.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.java:14)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.reword.RewordInterceptor.intercept(RewordInterceptor.java:13)
       at dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at dev.b3nedikt.viewpump.ViewPump.inflate(ViewPump.java:38)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2.onCreateView(-ViewPumpLayoutInflater.java:365)
       at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:51)
       at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:428)
       at android.widget.ArrayAdapter.getView(ArrayAdapter.java:419)
       at android.widget.AbsListView.obtainView(AbsListView.java:2452)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1426)
       at android.widget.ListView.onMeasure(ListView.java:1332)
       at android.view.View.measure(View.java:25007)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25007)
       at androidx.appcompat.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:134)
       at androidx.appcompat.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:64)
       at android.view.View.measure(View.java:25007)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
       at android.view.View.measure(View.java:25007)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25007)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25007)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25007)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7018)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:805)
       at android.view.View.measure(View.java:25007)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3490)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2139)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2470)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2050)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
       at android.view.Choreographer.doCallbacks(Choreographer.java:881)
       at android.view.Choreographer.doFrame(Choreographer.java:808)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7830)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
```
This comes together with this:
`android.view.InflateException: Binary XML file line #23 in layout/select_dialog_item_material: Error inflating class TextView`
_select_dialog_item_material_ comes with google material library (we use 1.1.0-rc01). Devices which have this exception: Samsung J4+,S6,A21s . Oppo F11 Pro and some no name brands.

**Comment by B3nedikt** [comment]
@edgar-zigis activated issues for the repository
