### ISSUE TITLE
Crash when opening AlertDialog

### ISSUE THREAD

**Issue by edgar-zigis** [B3nedikt/restring#56]
It looks like that the other crashes are fixed, but there is one left. App crashes _on some_ devices when opening AlertDialog.
The exact crash:
```
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x0
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:228)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2170)
       at android.content.res.Resources.getLayout(Resources.java:1170)
       at dev.b3nedikt.restring.internal.RestringResources.getLayout(RestringResources.java:162)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
       at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:51)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
       at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
       at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
       at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:550)
       at android.app.Dialog.show(Dialog.java:391)
       at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
```
`Crashing devices:` Samsung S8, S10e, A40 and Xiaomi Redmi 5A

**Comment by edgar-zigis** [comment]
Can't reproduce this though myself on my Samsung S7. This is how the actual piece of code looks like:
```
AlertDialog.Builder(context)
    .setTitle(context.getString(R.string.attention))
    .setMessage(R.string.some_message)
    .setCancelable(false)
     .setPositiveButton(context.getString(R.string.ok)) { dialog, _ ->
          dialog.cancel()
     }.show().apply {
         getButton(AlertDialog.BUTTON_POSITIVE).setTextColor(ContextCompat.getColor(context, R.color.blue))
     }
```

**Comment by B3nedikt** [comment]
@edgar-zigis 
I think the issue is in AlertController Line 191:
```
 mAlertDialogLayout = a.getResourceId(R.styleable.AlertDialog_android_layout, 0);
```
The RestringResources don't return a valid resource id here, so 0 is used as default value, which leads to above crash. Not sure why though, I can't reproduce the issue on my Xiaomi Note 10.

One potential cheat solution would be to copy&paste the code from R.styleable.AlertDialog_android_layout into your project, inflate it yourself, and provide it to the AlertDialog.Builder(...).setView(...) method ;)

Btw. are you using the framework AlertDialog or the one from appcompat?

**Comment by edgar-zigis** [comment]
Hey, it was `androidx.appcompat.app.AlertDialog`. I just have decided to replace it with just `android.app.Dialog` and now everything is fine.

**Comment by B3nedikt** [comment]
Think the actual reason for the crash is related to the Theme the context has when creating the AlertDialog. But this may be specific for your app, as I can't recreate it with my Samsung S8, so closed for now ;)
