### ISSUE TITLE
Strings accessed using application context are not getting override

### ISSUE THREAD

**Issue by iamsapnasharma** [B3nedikt/restring#57]

**Comment by B3nedikt** [comment]
As written in the Readme, if you want to do use strings from application context, you also need to wrap it.

Your Application class will look something like this then:

```
class SampleApplication : Application() {

    override fun onCreate() {
        super.onCreate()

        Restring.init(this)

        ViewPump.init(ViewPump.builder()
                .addInterceptor(RewordInterceptor)
                .build()
        )
    }

    override fun getApplicationContext(): Context {
        return Restring.wrapContext(super.getApplicationContext())
    }

    override fun getResources(): Resources {
        return Restring.wrapContext(baseContext).resources
    }
}
```

**Comment by iamsapnasharma** [comment]
Hi @B3nedikt 

If I'm adding 

  @Override
    public Resources getResources() {
        return Restring.wrapContext(getBaseContext()).getResources();
    }

    @Override
    public Context getApplicationContext() {
        return Restring.wrapContext(super.getApplicationContext());
    }

in my application class, my app is getting crashed. Crash logs are given below:

  java.lang.RuntimeException: Unable to get provider androidx.lifecycle.ProcessLifecycleOwnerInitializer: kotlin.UninitializedPropertyAccessException: lateinit property stringRepository has not been initialized
        at android.app.ActivityThread.installProvider(ActivityThread.java:6242)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property stringRepository has not been initialized
        at dev.b3nedikt.restring.Restring.wrapContext(Restring.kt:110)
        at com.vineretail.main.AppController.getResources(AppController.java:106)
        at dev.b3nedikt.restring.Restring.wrapContext(Restring.kt:109)
        at com.vineretail.main.AppController.getApplicationContext(AppController.java:111)
        at androidx.lifecycle.LifecycleDispatcher.init(LifecycleDispatcher.java:43)
        at androidx.lifecycle.ProcessLifecycleOwnerInitializer.onCreate(ProcessLifecycleOwnerInitializer.java:37)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239)

**Comment by B3nedikt** [comment]
It seems you are initializing your AppController class before calling Restring.init(this). As the AppController class seems to depend on accessing strings from Restring, this will not work, you need to call Restring.init(this) first.

See here:
```
at dev.b3nedikt.restring.Restring.wrapContext(Restring.kt:109)
at com.vineretail.main.AppController.getApplicationContext(AppController.java:111)
```

The crash itself should have been fixed in Restring 5.1.0 though, this may be a regression. Do you use the latest version of Restring?

**Comment by iamsapnasharma** [comment]
No, I was using 5.0.1. After updating to 5.1.0, the crash is no more also I'm able to use strings from application context.
Thanks so much!!

**Comment by B3nedikt** [comment]
You're welcome :)
