### ISSUE TITLE
onGetLayoutInflater throws IllegalStateException: A factory has already been set on this LayoutInflater

### ISSUE THREAD

**Issue by onebird100** [B3nedikt/restring#58]
Hello,

I am targeting API 29, using the AndroidX support library. Minimum target is API 19.

Adding this
`override fun onGetLayoutInflater(savedInstanceState: Bundle?): LayoutInflater {
        val wrappedContext = ViewPumpContextWrapper.wrap(Restring.wrapContext(requireContext()))
        return wrappedContext.getSystemService(Context.LAYOUT_INFLATER_SERVICE) as LayoutInflater
    }`

to my BaseFragment results in the error

`java.lang.RuntimeException: Unable to start activity ComponentInfo{******}: java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
        at android.view.LayoutInflater.setFactory(LayoutInflater.java:298)
        at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.setFactory(-ViewPumpLayoutInflater.kt:83)
        at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.setUpLayoutFactories(-ViewPumpLayoutInflater.kt:76)
        at dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater.<init>(-ViewPumpLayoutInflater.kt:35)
        at dev.b3nedikt.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:25)
        at dev.b3nedikt.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:22)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at dev.b3nedikt.viewpump.ViewPumpContextWrapper.getInflater(ViewPumpContextWrapper.kt)
        at dev.b3nedikt.viewpump.ViewPumpContextWrapper.getSystemService(ViewPumpContextWrapper.kt:31)
        at com.shirishanu.apps.ipvc.outgrower.BaseFragment.onGetLayoutInflater(BaseFragment.java:23)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1484)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2722)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
        at android.app.Activity.performStart(Activity.java:6679)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)`

Also I switched to rewword 2.0.1 instead of 2.0.2 because gradle couldn't find the newer version

**Comment by B3nedikt** [comment]
@onebird100 So you are using not the androidX appcompat library, but the old support libraries?
Can you post the artifacts you are using?

**Comment by B3nedikt** [comment]
@onebird100  The issue with 2.0.2 not getting found is fixed, thanks for reporting :)

**Comment by onebird100** [comment]
> @onebird100 So you are using not the androidX appcompat library, but the old support libraries?
> Can you post the artifacts you are using?

I am using the new androidX support libraries. Forgive me, English is not my first language so I'm not sure what you mean by "artifacts". I'm guessing you mean my gradle dependencies.


`  
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.preference:preference:1.1.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'`
   
    def nav_version = "2.3.0"

    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"

    def room_version = "2.2.5"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

    def work_version = "2.4.0"
    implementation "androidx.work:work-runtime:$work_version"

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    implementation project(path: ':main')

    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.jakewharton:disklrucache:2.0.2'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    implementation 'com.jcminarro:Philology:2.1.0'
    implementation 'io.github.inflationx:viewpump:2.0.3'

    // Allows to update the text of views at runtime without recreating the activity
    implementation 'dev.b3nedikt.reword:reword:2.0.1'
`

Thank you for taking the time to look at my issue. From what I could deduce, the LayoutInflater (for Viewpump) is set somewhere inside ViewPumpContextWrapper.kt. I take it that this makes it possible to intercept the strings during inflation for Restring can change the text accordingly. A bit of googling took me to this [stackoverflow question](https://stackoverflow.com/a/29903311/8252265) which talks about `LayoutInflater.setFactory()` being deprecated and has been replaced by `LayoutInflaterCompat.setFactory()`. I'm not even sure if this is what is happening or if it makes sense in any way in this library, but I just felt that may be some helpful information.

One more thing my project is in Java, not sure if that is relevant as well.

**Comment by B3nedikt** [comment]
@onebird100 You're welcome, yeah artifacts means gradle dependencies here :)
Also you are mostly right about the way restring & ViewPump work. The only thing you misunderstood I think is that restring depends on ViewPump, while it does not. You can use restring entirely without ViewPump & reword. ViewPump is needed to use the Reword library, which enables you to update strings without restarting the activity.

You are using the old appcompat 1.0.0, where you don't need to add this to your fragments:

```
abstract class BaseFragment : Fragment() {

    override fun onResume() {
        super.onResume()

        ViewPump.setOverwriteContext(Restring.wrapContext(requireContext()))
    }

    override fun onGetLayoutInflater(savedInstanceState: Bundle?): LayoutInflater {
        val wrappedContext = ViewPumpContextWrapper.wrap(Restring.wrapContext(requireContext()))
        return wrappedContext.getSystemService(Context.LAYOUT_INFLATER_SERVICE) as LayoutInflater
    }
}
```

Just remove it and everything should work.

I would suggest updating your libs in the long term though, appcompat 1.0.0 has a few known bugs with night mode, webviews etc... Some other libs you are using are also outdated. Also "Philology" & the version of viewpump you are using are not supported by reword 2.x.x, you need to use a old 1.x.x version. I am not sure why you are using Philology anyway, when using my lib, as they kind of do the same thing, so either restring or Philology would be enough ;)

**Comment by onebird100** [comment]
I updated Reword to 2.0.2, removed Philology and removed the above code as you suggested and everything started to work. Thank you.
