### ISSUE TITLE
Crash while using TabItem

### ISSUE THREAD

**Issue by prateekvijay** [B3nedikt/restring#79]
Logs:
     Caused by: android.view.InflateException: Binary XML file line #7 in com.peoplehum.app:layout/activity_recruit_home: Binary XML file line #25 in com.peoplehum.app:layout/layout_common_tab: Error inflating class com.google.android.material.tabs.TabItem
     Caused by: android.view.InflateException: Binary XML file line #25 in com.peoplehum.app:layout/layout_common_tab: Error inflating class com.google.android.material.tabs.TabItem
     Caused by: java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
        at dev.b3nedikt.reword.creator.TabItemViewCreator.createView(TabItemViewCreator.kt:25)
        at dev.b3nedikt.reword.creator.TabItemViewCreator.createView(TabItemViewCreator.kt:13)
        at dev.b3nedikt.reword.ViewTransformerManager.createView(ViewTransformerManager.kt:47)
        at dev.b3nedikt.reword.RewordInterceptor.intercept(RewordInterceptor.kt:19)
        at dev.b3nedikt.viewpump.internal.InterceptorChain.proceed(InterceptorChain.kt:37)
        at androidx.appcompat.app.ViewPumpAppCompatDelegate.inflate(ViewPumpAppCompatDelegate.kt:97)
        at androidx.appcompat.app.ViewPumpAppCompatDelegate.createView(ViewPumpAppCompatDelegate.kt:47)
        at androidx.appcompat.app.ViewPumpAppCompatDelegate.onCreateView(ViewPumpAppCompatDelegate.kt:83)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.peoplehum.app.base.BaseActivity.setBaseNavigationBarContentView(BaseActivity.kt:192)
        at com.peoplehum.app.features.recruit.view.activity.RecruitHomeActivity.onCreate(RecruitHomeActivity.kt:52)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
2021-01-27 17:27:21.600 20804-20804/com.peoplehum.app E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2021-01-27 17:27:21.603 20804-20804/com.peoplehum.app E/Log: App crashed :java.lang.RuntimeException: Unable to start activity ComponentInfo{com.peoplehum.app/com.peoplehum.app.features.recruit.view.activity.RecruitHomeActivity}: android.view.InflateException: Binary XML file line #7 in com.peoplehum.app:layout/activity_recruit_home: Binary XML file line #25 in com.peoplehum.app:layout/layout_common_tab: Error inflating class com.google.android.material.tabs.TabItem , Thread is : main

**Comment by B3nedikt** [comment]
@prateekvijay I just fixed this in Reword 3.1.1 :)
